version: 2
deploy-job:
  working_directory: ~/website/

  environment:
  - CI: false

  docker:
  - image: circleci/node:8.10-browsers

  steps:
  - checkout

  - restore_cache:
      key: ee-client-{{ checksum "./web/package.json" }}
      key: ee-functions-{{ checksum "./functions/package.json" }}

  - run:
      name: Acceptance Test
      command: |
        cd ./web
        npm run acceptance-test

  - save_cache:
      key: ee-build-{{ checksum "./web/package.json" }}
      paths:
      - ./web/node_modules

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/website/

    steps:
      - checkout:
          path: ~/website/

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install packages
          command: |
            npm install

      - run:
          name: Test
          command: |
            npm run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build project
          command: |
            if [ "${CIRCLE_BRANCH}" == "release"]; then
              npm run build
            else
              STAGING=true npm run build
            fi

      - deploy:
          name: Deploy to Firebase if tests pass
          command: |
            case "${CIRCLE_BRANCH}" in
              "master")
              ./node_modules/.bin/firebase use website-staging
                ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
              ;;
              "release")
                ./node_modules/.bin/firebase use website-production
                ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
              ;;
              *) echo "No deployment target available for branch ${CIRCLE_BRANCH}"; ;;
            esac;
