version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/website/
    steps:
      - checkout:
          path: ~/website/
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build project
          command: |
            if [ "${CIRCLE_BRANCH}" == "release"]; then
              npm run build
            else
              STAGING=true npm run build
            fi

      - deploy:
          name: Deploy to Firebase if tests pass
          command: |
            case "${CIRCLE_BRANCH}" in
              "master")
              ./node_modules/.bin/firebase use website-staging
                ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
              ;;
              "release")
                ./node_modules/.bin/firebase use website-production
                ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
              ;;
              *) echo "No deployment target available for branch ${CIRCLE_BRANCH}"; ;;
            esac;
